site_name: XAUTOMATA Documentation
site_description: Documentation for the use of XAUTOMATA Services
site_url: https://www.xautomata.com/

theme:
  favicon: images/logo.png
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.follow
    - header.autohide

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: blue

repo_name: XAUTOMATA User Interface Documentation

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:

  - Home: index.md
  - Platform Concepts:
      - System Overview: system_overview.md
      - Platform Models: platform_models.md
      - Monitoring Lifecycle: monitoring_lifecycle.md
      - Metrics and Metric Types: metrics_model.md
      - Monitoring Architecture: monitoring_architecture.md

  - Access:
      - Login: Login.md

  - User Interface:
      - Overview: ui_overview.md
      - Navigation: navigation.md

  - Data Manager:
      - Overview: data_manager_overview.md
      - Working with Entities: working_with_entities.md
      - Tree Hierarchy View: tree_hierarchy_view.md

      - Customers:
          - Customers: customers.md
          - Sites: sites.md
          - Contacts: contacts.md

      - Objects Repository:
          - Groups: groups.md
          - Objects: objects.md
          - Metric Types: metric_types.md
          - Metrics: metrics.md
          - Services: services.md

      - Monitoring Operations:
          - Calendars: calendars.md
          - Downtimes: downtimes.md
          - Dispatchers: dispatchers.md

  - Dashboards:
      - Dashboard Overview: dashboards_overview.md
      - IT Infrastructure: it_infrastructure.md
      - Network: network_dashboard.md
      - Cloud Cost: cloudcost_dashboard.md

  - Cost Management:
      - Overview: cost_management_overview.md
      - Cloud Cost Registration: cloud_cost_registration.md
      - Cost Views: cost_views.md

  - Widgets:
      - Widget Overview: widget_overview.md

      - Infrastructure Monitoring:
          - IT Infrastructure: widget_it_infrastructure.md
          - IT Analytics: widget_it_analytics.md
          - IT Anomalies: widget_it_anomalies.md

      - Network Governance:
          - Network: widget_network.md
          - Network Analytics: widget_network_analytics.md
          - Net Flow: widget_net_flow.md

      - Service Management:
          - Support Service KPI: widget_support_service_kpi.md

      - Cost Governance:
          - Cloud Cost: widget_cloudcost.md
          - Analytical Accounting: widget_analytical.md

      - Dedicated Widgets:
          - MCD Dedicated: widget_mcd_dedicated.md
          - MCD Massive Reboot: widget_mcd_reboot.md
          - MCD Rebuild VM: widget_mcd_rebuild_vm.md
          - MCD Massive Downtime: widget_mcd_downtime.md

  - Administration:
      - Overview: administration_overview.md
      - Users: users.md
      - Virtual Domains: virtual_domains.md
      - Probes: probes.md
      - Probe Types: probe_types.md
      - Messages: messages.md
      - Notification Providers: notification_providers.md
      - Notification Provider Types: notification_provider_types.md

  - Super Admin:
      - Widgets: admin_widgets.md
      - Widget Groups: admin_widget_groups.md
      - Dashboards: admin_dashboards.md
      - ACL Overrides: acl_overrides.md

copyright:
  All rights reserved
